<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-10-20 11:02
=======
# Generated by Django 4.1.2 on 2022-10-20 11:13
>>>>>>> 0aed837ae91d9e27719f6f37a8b5dba91daa5f13

from django.db import migrations, models
import django.db.models.deletion
import tweet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to=tweet.models.Article.date_upload_to)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TweetComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tweet.article')),
            ],
        ),
<<<<<<< HEAD
        migrations.AddField(
            model_name='article',
            name='taghash',
            field=models.ManyToManyField(related_name='tagged', to='tweet.tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
=======
>>>>>>> 0aed837ae91d9e27719f6f37a8b5dba91daa5f13
    ]
