# Generated by Django 4.1.2 on 2022-10-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tagname',
            field=models.CharField(max_length=20),
        ),
    ]
