# Generated by Django 4.1.2 on 2022-10-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_alter_tag_tagname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='taghash',
            field=models.ManyToManyField(related_name='tagged', to='tweet.tag'),
        ),
    ]
