# Generated by Django 4.1.2 on 2022-10-18 02:38

from django.db import migrations, models
import tweet.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to=tweet.models.Article.date_upload_to),
        ),
    ]
