# Generated by Django 4.1.2 on 2022-10-20 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_initial'),
        ('tweet', '0003_alter_article_taghash'),
    ]

    operations = [
    ]
