# Generated by Django 4.1.2 on 2022-10-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_alter_article_taghash'),
        ('tweet', '0005_article_user'),
    ]

    operations = [
    ]
