# Generated by Django 4.1.2 on 2022-10-20 11:42

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_users_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(default='profile/default_profile', null=True, upload_to=user.models.Users.date_upload_to),
        ),
    ]
